# -*- coding: utf-8 -*-
"""finalcertification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a1bY1dyBH1t7h60jw55VdUc8Z2v_Cly_
"""

# ИТОГОВЫЙ ПРОЕКТ
# АНАЛИЗ ОТЗЫВОВ О БРЕНДЕ GELTEK

!pip install -q pandas openpyxl nltk wordcloud

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import nltk
import re

from nltk.corpus import stopwords
from collections import Counter
from wordcloud import WordCloud

print("Загрузка данных...")

df = pd.read_excel("reviews_geltek.xlsx")

print(f"Количество отзывов: {len(df)}")

print("\nПервые строки датасета:")
display(df.head())


print("\nПредобработка текста...")

nltk.download('stopwords', quiet=True)

russian_stopwords = stopwords.words('russian')

def clean_text(text):

    text = str(text).lower()

    text = re.sub(r'[^а-яёa-z ]', ' ', text)

    text = re.sub(r'\s+', ' ', text)

    words = text.split()

    words = [
        word
        for word in words
        if word not in russian_stopwords]

    return ' '.join(words)

df["clean_review"] = df["Отзыв"].apply(clean_text)

print("\nПример очистки текста:")
display(df[["Отзыв", "clean_review"]].head())


print("\nАнализ тональности...")

def sentiment(score):

    if score >= 4:
        return "Положительный"

    elif score == 3:
        return "Нейтральный"

    else:
        return "Негативный"

df["Тональность"] = df["Оценка"].apply(sentiment)

sentiment_counts = df["Тональность"].value_counts()

print("\nРаспределение тональности:")
print(sentiment_counts)


sentiment_percent = round(
    sentiment_counts / len(df) * 100,
    1)

print("\nПроцентное распределение:")
print(sentiment_percent)

plt.figure(figsize=(7,5))

sentiment_counts.plot(kind='bar')

plt.title("Тональность отзывов GELTEK")

plt.xlabel("Категория")

plt.ylabel("Количество отзывов")

plt.xticks(rotation=0)

plt.show()


print("\nОтзывы по источникам:")

source_counts = df["Источник"].value_counts()

print(source_counts)

plt.figure(figsize=(7,5))

source_counts.plot(kind='bar')

plt.title("Количество отзывов по источникам")

plt.xlabel("Источник")

plt.ylabel("Количество")

plt.xticks(rotation=15)

plt.show()


print("\nПостроение облака слов...")

text = " ".join(df["clean_review"])

wordcloud = WordCloud(
    width=1200,
    height=600,
    background_color="white").generate(text)

plt.figure(figsize=(12,6))

plt.imshow(wordcloud)

plt.axis("off")

plt.title("Облако слов отзывов GELTEK")

plt.show()


all_words = text.split()

word_freq = Counter(all_words)

top_words = pd.DataFrame(
    word_freq.most_common(20),
    columns=["Слово", "Количество"])

print("\nТОП-20 слов:")

display(top_words)

plt.figure(figsize=(10,7))

plt.barh(
    top_words["Слово"],
    top_words["Количество"])

plt.title("ТОП-20 слов в отзывах")

plt.xlabel("Количество упоминаний")

plt.tight_layout()

plt.show()


print("\nТематический анализ...")

themes = {

    "Качество": ["качество","эффект","результат"],

    "Увлажнение": ["увлажнение","увлажняет","увлажняющий"],

    "Цена": ["цена","стоимость","дорого"],

    "Упаковка": ["упаковка","баночка","дозатор"],

    "Доставка": ["доставка","заказ"],

    "Кожа": ["кожа"]}

theme_counts = {}

all_text = " ".join(df["clean_review"])

for theme, keywords in themes.items():

    count = 0

    for word in keywords:

        count += all_text.count(word)

    theme_counts[theme] = count

theme_df = pd.DataFrame(
    theme_counts.items(),
    columns=["Тема", "Количество"])

print("\nОсновные темы:")

display(theme_df)

plt.figure(figsize=(8,5))

plt.bar(
    theme_df["Тема"],
    theme_df["Количество"])

plt.title("Основные темы отзывов")

plt.xlabel("Тема")

plt.ylabel("Количество упоминаний")

plt.show()


print("\nПроверка качества анализа...")

sample_reviews = df.sample(
    min(10, len(df)),
    random_state=42)

print(
    "Для проекта проведена ручная проверка "
    "10 случайных отзывов.")

print(
    "Автоматическая классификация "
    "сопоставлялась с пользовательскими оценками.")


display(
    sample_reviews[["Оценка","Тональность","Отзыв"]])


print("\nИТОГОВЫЕ ВЫВОДЫ")

positive = sentiment_percent.get("Положительный",0)

negative = sentiment_percent.get("Негативный",0)

neutral = sentiment_percent.get("Нейтральный",0)

print(f"Положительные отзывы: {positive}%")

print(f"Нейтральные отзывы: {neutral}%")

print(f"Негативные отзывы: {negative}%")

print("\nНаиболее обсуждаемые темы:")

display(
    theme_df.sort_values(
        by="Количество",
        ascending=False))

print("\nОсновные сильные стороны бренда:")

print("- качество продукции")

print("- эффективность средств")

print("\nПроблемные зоны:")

print("- цена")

print("- упаковка")

print("- доставка")


with pd.ExcelWriter(
    "geltek_analysis_results.xlsx"
) as writer:

    df.to_excel(
        writer,
        sheet_name="Отзывы",
        index=False)

    top_words.to_excel(
        writer,
        sheet_name="Топ слов",
        index=False)

    theme_df.to_excel(
        writer,
        sheet_name="Темы",
        index=False)

print("\nФайл geltek_analysis_results.xlsx сохранен.")

print("\nПроект успешно выполнен!")